# Generated by Django 5.0.1 on 2024-01-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
